version: '3'
services:
  android-emulator:
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
    devices:
      - /dev/kvm
  flutter-app:
    container_name: flutter-app
    depends_on:
      - android-emulator
    build:
      context: .
      dockerfile: ./flutter_TodoList/BuildAndTest.Dockerfile

    # Additional configuration for the Flutter app container

#   nodejs-project:
#     container_name: nodejs-project
#     build:
#       context: .
#       dockerfile: nodeJsTodoList/runAndTest.Dockerfile
#     # Additional configuration for the Node.js project container

